---
version: "2"

plugins:
  # duplication:
  #   enabled: true
  eslint:
    enabled: true
    channel: "eslint-8"
  # reek:
  #   enabled: true
  # rubocop:
  #   enabled: true
  #   channel: "beta"
  # structure:
  #   enabled: true
  stylelint:
    enabled: true
    exclude_patterns:
      - "**/app/assets/builds/tailwind.css"
