---
EnableDefaultLinters: true
exclude:
  - '**/vendor/**/*'
  - '**/_*.html.erb'
  - '**/app/views/stats/days/show.html.erb' # TODO

linters:
  # TODO
  ErbSafety:
    exclude:
      - '**/app/views/shared/_flashes.html.erb'
      - '**/app/components/header/nav_component.html.erb'

  # Disable "String not translated" errors while passing the --enable-all-linters flag
  HardCodedString:
    exclude:
      - '**/app/components/**/*'
      - '**/app/components/*'
      - '**/app/views/**/*'

  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/InitialIndentation:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Rails/OutputSafety:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
