require:
  - rubocop-performance
  - rubocop-rails
  # - rubocop-rspec
  # - rubocop-rspec_rails
  # - rubocop-factory_bot

AllCops:
  NewCops: enable

Lint/MissingSuper:
  Exclude:
    - "**/app/components/**/*"

Lint/SymbolConversion:
  EnforcedStyle: consistent

Naming/VariableNumber:
  EnforcedStyle: snake_case

Rails/DangerousColumnNames:
  Exclude:
    - "**/db/migrate/20221010144700_make_cache_key_more_obvious_in_cache_models.rb"
    - "**/db/migrate/20221024015351_change_cache_keys_to_strings_and_change_their_name.rb"

Rails/DynamicFindBy:
  AllowedMethods: ["find_by_referral_code"]

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/StringLiterals:
  EnforcedStyle: double_quotes


## Disabled cops

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Style/Documentation:
  Enabled: false
