require:
  - rubocop-performance
  - rubocop-rails
  # - rubocop-rspec

AllCops:
  NewCops: enable

Layout/LineLength:
  Enabled: false

Lint/MissingSuper:
  Exclude:
    - "**/app/components/**/*"

Lint/SymbolConversion:
  EnforcedStyle: consistent

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength: # TODO: remove after old files are deprecated
  Enabled: false

Metrics/CyclomaticComplexity:
  Exclude:
    - "**/app/controllers/days_controller.rb"
    - "**/app/controllers/users_controller.rb"

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Exclude:
    - "**/app/controllers/days_controller.rb"

Naming/VariableNumber:
  EnforcedStyle: snake_case

Rails/I18nLocaleTexts:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/StringLiterals:
  EnforcedStyle: double_quotes
