require:
  - rubocop-performance
  - rubocop-rails
  # - rubocop-rspec

AllCops:
  NewCops: enable

Lint/MissingSuper:
  Exclude:
    - "**/app/components/**/*"

Lint/SymbolConversion:
  EnforcedStyle: consistent

Metrics/ClassLength:
  Exclude:
    - "**/app/models/user.rb"

Naming/VariableNumber:
  EnforcedStyle: snake_case
  Exclude:
    - "**/app/controllers/messages_controller.rb"
    - "**/app/domains/completions/fetcher.rb"

Rails/DangerousColumnNames:
  Exclude:
    - "**/db/migrate/*"

Rails/DynamicFindBy:
  AllowedMethods: ["find_by_referral_code"]

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/StringLiterals:
  EnforcedStyle: double_quotes


## Disabled cops

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Style/Documentation:
  Enabled: false
