require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable

Layout/LineLength:
  Enabled: false

Lint/NestedMethodDefinition:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/VariableNumber:
  EnforcedStyle: snake_case

Rails/BulkChangeTable:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/StringLiterals:
  EnforcedStyle: double_quotes
