services:
  app: &app
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - tailwindcss:/app/app/assets/builds
      - postgres_socket:/var/run/postgresql

  db:
    image: postgres:14.2-alpine
    container_name: aoc-db
    command: "postgres -c 'max_connections=500'"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_socket:/var/run/postgresql

  web:
    <<: *app
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      PIDFILE: /tmp/pids/server.pid
    ports:
      - "3000:3000"
    depends_on:
      - db
    tmpfs:
      - /tmp/pids
  worker:
    <<: *app
    command: "bundle exec good_job start"
    depends_on:
      - db
  css:
    <<: *app
    tty: true
    command: "bundle exec rails tailwindcss:watch"

volumes:
  postgres_data: {}
  bundle: {}
  tailwindcss: {}
  postgres_socket: {}
networks:
  default:
    name: aoc_default
