services:
  app: &app
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment: &env
      DATABASE_URL: postgres://aoc:aoc@db:5432/aocdb
    volumes: &volumes
      - .:/app
      - bundle:/usr/local/bundle
      - tailwindcss:/app/app/assets/builds

  db:
    image: postgres:14.2-alpine
    container_name: aoc-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    environment:
      POSTGRES_DB: aocdb
      POSTGRES_USER: aoc
      POSTGRES_PASSWORD: aoc
    ports:
      - "5432:5432"

  web:
    <<: *app
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      <<: *env
      PIDFILE: /tmp/pids/server.pid
    ports:
      - "3000:3000"
    depends_on:
      - db
    tmpfs:
      - /tmp/pids
  worker:
    <<: *app
    command: "bundle exec good_job start"
    depends_on:
      - db
  css:
    <<: *app
    tty: true
    command: "bundle exec rails tailwindcss:watch"

volumes:
  postgres_data: {}
  bundle: {}
  tailwindcss: {}
networks:
  default:
    name: aoc_default
