name: Deploy production
on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Scaleway Dokku
        uses: dokku/github-action@master
        with:
          command: deploy
          git_remote_url: "ssh://dokku@aoc.lewagon.engineering/aoc"
          git_push_flags: "--force -vvv"
          ssh_private_key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
          ssh_host_key: |
            aoc.lewagon.engineering ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBSrD6AdnGUx4U9vveaTF+pBGjujy2GABWd7wkGfrm9l
