---
name: Fly Deploy (PR)

on:
  pull_request:

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    # Deploy any push on any Pull Request to https://lewagon-aoc-pr.fly.dev/

      name: Deploy app
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: fly postgres detach lewagon-aoc-db                                              --app lewagon-aoc-pr || true
        - run: fly apps destroy lewagon-aoc-pr --yes                                                                || true
        - run: fly apps create --name lewagon-aoc-pr                                                               
        - run: fly postgres attach lewagon-aoc-db --database-user=$(uuidgen | tr -d -) --force --app lewagon-aoc-pr
        - run: fly secrets set AAARGHH_THIS_IS_STAGING=1                                       --app lewagon-aoc-pr
        - run: fly deploy                                                                      --app lewagon-aoc-pr
        - run: fly scale memory 512                                                            --app lewagon-aoc-pr
        - run: fly ssh console -C "app/bin/rails db:seed"                                      --app lewagon-aoc-pr
