---
name: Fly Deploy (PR)

on:
  pull_request:

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    # Deploy any push on any Pull Request to https://lewagon-aoc-pr.fly.dev/

      name: Deploy app
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl postgres detach lewagon-aoc-db                                    --app lewagon-aoc-pr  --verbose || true
        - run: flyctl apps destroy lewagon-aoc-pr --yes                                                       --verbose
        - run: flyctl apps create --name lewagon-aoc-pr                                                       --verbose
        - run: |
          UUID=$(uuidgen | tr -d - | tr '[:upper:]' '[:lower:]')
          flyctl postgres attach lewagon-aoc-db --database-user=$UUID --force --app lewagon-aoc-pr  --verbose
        - run: flyctl deploy --env AAARGHH_THIS_IS_STAGING=1                            --app lewagon-aoc-pr  --verbose
        - run: flyctl scale memory 512                                                  --app lewagon-aoc-pr  --verbose
        - run: flyctl ssh console -C "app/bin/rails db:seed"                            --app lewagon-aoc-pr  --verbose
